[package]
name = "overberg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytesize = "1.3.0"
iced = { git = "https://github.com/iced-rs/iced.git", rev = "eaaea414", features = ["system"] }
