[package]
name = "proto"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
serde = { version = "1.0.193", default-features = false, features = ["derive"] }

[features]
std = ["serde/std"]

default = ["std"]
